#!/bin/sh
#
# Start the bluetooth pan ap network....
#
BT_DEFAULTKEY_FILE="/etc/init.d/bt_defaultkey"

case "$1" in
  start)
  	if [ -f $BT_DEFAULTKEY_FILE ] && [ -f /etc/init.d/bt_name ]
        then
 	    echo "Starting bluetooth NAP..."
	    BTMAC=`hciconfig hci0 | grep BD\ Address\: | cut -d ' ' -f 3`
	    BTDIR=/var/lib/bluetooth/$BTMAC
 	    BTNAME=`cat /etc/init.d/bt_name`
 	    echo "$BTMAC $BTNAME $BTDIR"
 	
 	    hciconfig hci0 up piscan lm master,accept class 0x020300
	    hciconfig hci0 sspmode 0 # for fixed pin pairing
	    hciconfig hci0 auth #for fixed pin pairing

 	    /usr/libexec/bluetooth/bluetoothd --compat --noplugin=sap &

 	    if [ ! -L /sys/class/net/pan0 ]
 	    then
 	        brctl addbr pan0
 	        brctl setfd pan0 0
 	        brctl stp pan0 off
		ip addr add 192.168.9.2/24 dev pan0
		ip link set pan0 up
 	    fi  
	    #----
 	    #-- Pairing agent
  	    BT_DEFAULTKEY=`cat $BT_DEFAULTKEY_FILE`
	    #-- Pairing Agent starten
	    echo "* $BT_DEFAULTKEY" > /tmp/bt_pincodes
	    bt-agent -c KeyboardOnly -p /tmp/bt_pincodes &
	    #-- SER Start
	    sdptool add --channel 22 SP
	    /etc/init.d/bt_ser &
 	    #-- NAP Server Starten
            if [ ! -f /etc/init.d/bt_ap_on ]
            then
  	        touch /etc/init.d/bt_ap_on
            fi
            sleep 5
	    bluetoothctl discoverable yes
	    bluetoothctl show
	    bt-pan --debug server pan0 &
  	else
  	    echo "Bluetooth name or pairing key not set"
  	fi
	;;
	
  stop)
	echo -n "Stopping bluetooth NAP..."
	killall -SIGTERM bt_ser
	killall -SIGTERM rfcomm
	killall -SIGTERM bt-agent
	killall -SIGTERM bluetoothd
	hciconfig hci0 down
 	rm /etc/init.d/bt_ap_on
	;;
	
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
