#!/bin/sh

start() {
	printf "Starting civetweb: "
	start-stop-daemon -S -q -m -b -p /var/run/civetweb.pid \
		--exec /usr/bin/civetweb /etc/civetweb.conf
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping civetweb: "
	start-stop-daemon -K -q -p /var/run/civetweb.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
