#!/bin/sh
#
# Start the vncserver....
#

case "$1" in
  start)
 	echo "Starting vncserver..."
	fbvncserver 2>/dev/null &
	;;
  stop)
	echo -n "Stopping vncserver..."
	killall fbvncserver
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

